### PR TITLE
Submit move

### PR DESCRIPTION
**Pull request by benbrunton**
Opened for comment, not looking to get this merged straight away.

- Have pulled out comparisons into it's own module.
- Round looks after general validation of submitted hand and reports back detailed error

### CODE REVIEW

**Comment by Roybie** [comment]
Things to consider:
Do we have comparison entirely in one place? Move validity depends on more than just last hand, next hand and the orders.
Current player, first move or not (do we need to lead with a hand containing 3♣) are the main ones that come to mind.

Having `game` check that the correct player is making the move, `round` checking the first move status and making sure the number of cards is the same as the previous hand, and then `comparison` just checking equal size hands against the order is a bit messy to me, and splitting too much makes bugs easier to appear.

But does comparison need to know current player, move number etc? Maybe.
What's the best balance is something that needs deciding.

**Comment by Roybie** [comment]
I think having the `comparison` just check equal sized hands and `round` doing the rest is probably most sensible (and what it seems like you're going for from this start).

Maybe a good way to do this part would be to write a bunch of tests first, since we have a good idea of the expected behaviour, more than the implementation details.

**Comment by benbrunton** [comment]
Well if I get a load of passing tests, we can modify the implementation once we have some of the functionality

**Comment by Roybie** [comment]
Yeah exactly

**Pull request merged**
